### ISSUE TITLE
dA did it again...

### ISSUE THREAD

**Issue by Koopzington** [KishanBagaria/dAbot#10]
Just tried running the bot and dA managed to find out that it is not a browser doing the requests again.
Tried changing the UserAgent strings in the code to see if it would fix the issue like last time but it seems to be something different now.
Interestingly i was able to login in using an incognito tab with disabled JS...
The HTML of the login form didn't show any sign of google recaptcha apart from an attribute `data-sigil="recaptcha-form"` on the form tag and references in js files.
Google's ReCaptcha can't be used without Javascript enabled though (at least the Invisible one) so i don't have a single clue what's going on here...
Maybe the HTML that the bot gets upon GETting the login form is already different from what browsers users will get?

**Comment by KishanBagaria** [comment]
Do you still face this issue? I just tried a new login and oddly, it worked for me now but it didn't 4 days ago when you commented.

**Comment by Koopzington** [comment]
huh... no... seems to be working again... guess dA's servers just had a hiccup.

**Comment by DRSDavidSoft** [comment]
@Koopzington This is because the bot detection is triggered on a score-based index basis, please read my explanation in #21 if you are still interested.
