### ISSUE TITLE
Using command in Python

### ISSUE THREAD

**Issue by ericlovesmath** [KishanBagaria/dAbot#12]
Ok. I'm bad a programming.
How can I run this through python?
```
os.system("say hi")       #Works
os.system("dAbot <MyUser> <MyPass> -v llama give <Username>")       #Nope. <>s have actual info
```

**Comment by KishanBagaria** [comment]
You can import the dAbot module and use a specific function. Google imports in Python.

Or you can prepend "python" and the Full path of the script in the code above.
