### ISSUE TITLE
Slowing down?

### ISSUE THREAD

**Issue by ericlovesmath** [KishanBagaria/dAbot#17]
Since the last 2 months, the speed that the code runs on seemed to... slow down by about 4 times?
It's not a wifi or computer issue, as it's the same on other devices and other networks

**Comment by Koopzington** [comment]
code doesn't simply run 'slower' for no particular reason. It's more likely that the servers of deviantArt are having higher response times than usual, maybe due to DDoSing or infrastructure migration.
