### ISSUE TITLE
Issues - gathering User names

### ISSUE THREAD

**Issue by jedaj666** [KishanBagaria/dAbot#18]
I understand that dabot can not find username in urls,
Because deviantart change username.deviantart.com   to  deviantart.com/username
This is also visible in the source of the page, on the list with deviants

I find this in code:
    'dev_names'            : r'([A-Za-z0-9-]+)\.deviantart\.com',

Its not correct i think... could you help me change this?  (i know i sucks)
'dev_names'            : r'\deviantart.com\([A-Za-z0-9-]+)',

**Comment by KishanBagaria** [comment]
I've updated it with the correct regex.

Not sure if it still works for you because DA is blocking automated logins.

**Comment by jedaj666** [comment]
Thx solved.  :)
