### ISSUE TITLE
Can i send llama to my/other deviant watchers ?

### ISSUE THREAD

**Issue by jedaj666** [KishanBagaria/dAbot#2]
1.I have a question if I can send a badge to my / other profile watchers on deviantart?
If yes - tell me how to do it ^^

2.What is the "hof"command ?

**Comment by KishanBagaria** [comment]
1. It doesn't have a dedicated command for that. But you can give a llama to someone's latest 100 watchers, using:
```
dAbot <username> <password> llama give url http://someone.deviantart.com/modals/watchers/
```
If you want to keep going after the latest 100 watchers, use:
```
dAbot <username> <password> llama give url http://someone.deviantart.com/modals/watchers/?offset=100
dAbot <username> <password> llama give url http://someone.deviantart.com/modals/watchers/?offset=200
```
And so on...

2. `hof` = Hall of Fame. It finds out the llama/badge stats of deviants and sorts them.

**Comment by jedaj666** [comment]
Thanks !
Another question: 
Is there any chance to retweet new watchers (in activity) Msg: "Thank you for watch"?

**Comment by KishanBagaria** [comment]
There's nothing that does specifically that but there's this command for commenting:
```
dAbot <username> <password> [-v] comment    <deviant>     <comment>
```
It might be faster than normal commenting, you have to try.
