### ISSUE TITLE
So the bot doesn't work anymore right?

### ISSUE THREAD

**Issue by jnpatrick99** [KishanBagaria/dAbot#20]
Seems DeviantArt has recently blocked all tools like this one. I get a message "Access to this page has been denied because we believe you are using automated tools to log into and browse DeviantArt."

Like in an old issue here: https://github.com/KishanBagaria/dAbot/issues/13 and here: https://github.com/KishanBagaria/dAbot/issues/19

Is there anything we can do?

**Comment by DRSDavidSoft** [comment]
@jnpatrick99 If you are still interested, I have written a patch for dAbot that allows you to bypass this message. Click here for details: #21.

**Comment by KishanBagaria** [comment]
I've updated it and the bot now works. Please read the README file for further instructions.
