### ISSUE TITLE
User collector

### ISSUE THREAD

**Issue by jedaj666** [KishanBagaria/dAbot#3]
Can dAbot collect dev username and save to file? 

Thanks  !!

**Comment by KishanBagaria** [comment]
No, the `random` command is not implemented completely.

**Comment by jedaj666** [comment]
I mean - can i gather dev user names from groups ?

**Comment by KishanBagaria** [comment]
You can try the `save group_members` command. Does that work?

**Comment by jedaj666** [comment]
Ok thanks. Can i save members using http://deviantauser.deviantart.com/modals/watchers/ ?
