### ISSUE TITLE
DAThrottlingError()

### ISSUE THREAD

**Issue by jedaj666** [KishanBagaria/dAbot#5]
12 Jul 2017
07:37:37.076 PM   [Llama Transactions] 0
07:37:37.076 PM   Checking if logged in as kay-ra
07:37:37.435 PM   Downloading login page
07:37:38.826 PM   Logging in as kay-ra
07:37:39.390 PM   Retrying... DAThrottlingError()

What does it mean and how can it be solved?
Thank you !

**Comment by KishanBagaria** [comment]
It means DA servers are throttling the requests. You can try browing DA on a browser and retry after a while.

**Comment by jedaj666** [comment]
Thanks !

**Comment by otmeek** [comment]
Is it a general thing with dA servers or is it done on an individual level? I have been getting this error for the past 2 days.

**Comment by KishanBagaria** [comment]
It's more likely to happen to accounts that are using bots. DA doesn't want the bots to send too much requests which will prevent them from serving regular humans well.

**Comment by otmeek** [comment]
Makes sense, thanks!

**Comment by HetaLilla** [comment]
I've been getting this error message for the past few days too. I think DeviantArt changed something because dAhub was also inactive for a while.
