### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by otmeek** [KishanBagaria/dAbot#7]
All features of dAbot have stopped working for me. Now, when attempting to login after "downloading login page" it literally outputs all html, css, js data of the dA page into the terminal and quits with the following:

```
Traceback (most recent call last):
  File "dAbot.py", line 803, in <module>
    main()
  File "C:\Python27\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Python27\lib\site-packages\retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "C:\Python27\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Python27\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "dAbot.py", line 667, in main
    if not login(username, password):
  File "dAbot.py", line 205, in login
    'validate_token' : get_validate_token(login_html),
  File "dAbot.py", line 178, in get_validate_token
    return r.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Press any key to exit...
```

**Comment by KishanBagaria** [comment]
Can reproduce. It doesn't happen if you're already logged in with dAbot.

It seems like DA has changed something and the login functionality is broken. The next update will fix this issue.

**Comment by otmeek** [comment]
Good to know an update is coming! Thanks!

**Comment by Koopzington** [comment]
Any update on that issue?

**Comment by KishanBagaria** [comment]
It's fixed now.

The login page originally said:
> Access to this page has been denied because we believe you are using automated tools to log into and browse DeviantArt.

Adding a `Accept-Language` header fixed it. They may use other means to detect bot activity in the future but for now, we're good. I've also updated the `User-Agent`.

**Comment by DRSDavidSoft** [comment]
@otmeek If this is still happening, please have a look at #21.
