### ISSUE TITLE
Bug due to https-migration

### ISSUE THREAD

**Issue by Koopzington** [KishanBagaria/dAbot#9]
When i logged into my computer this morning i saw several errors in my terminals stating that they couldn't request `https:///someuser.deviantart.com`
I've looked a bit through the code and saw that the username variables had a leading slash due to incorrect substringing [here](https://github.com/KishanBagaria/dAbot/blob/bc682d5b6e577fad66aea0e5016fce6e862e47a0/dAbot/dAbot.py#L190).

Replacing the 7 (`http://`) with an 8 (`https://`) fixed it for me.

**Comment by KishanBagaria** [comment]
Fixed, thanks!
